# Runs tests referencing the local GitHub Action to verify it works as intended.
---
name: Test

on:
  pull_request:
  push:
    branches-ignore:
      - "dependabot/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04
    name: Lint
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: j178/prek-action@cbc2f23eb5539cf20d82d1aabd0d0ecbcc56f4e3 # v2.0.2

  test_linkcheck:
    runs-on: ubuntu-24.04
    name: Test linkchecker and summariser
    timeout-minutes: 5

    strategy:
      # Keep running even if one variation of the job fail
      fail-fast: false
      matrix:
        sphinx_version:
          - 6
          - 7
          - 8
          - latest

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: tests/docs/requirements*.txt

      - name: Install dependencies
        run: |
          if [ ${{ matrix.sphinx_version }} = latest ]; then
            pip install -r tests/docs/requirements.txt
          else
            pip install Sphinx==${{ matrix.sphinx_version }}
          fi

      - name: Local action
        id: linkcheck
        uses: ./
        with:
          docs-dir: tests/docs
          build-dir: tests/docs/_build
          no-error: true

      - name: Verify outputs
        run: |
          EXIT=0
          if [[ "${STEPS_LINKCHECK_OUTPUTS_BROKEN_LINKS_COUNT}" != 1 ]]; then
              echo "Expected broken-links-count=1"
              EXIT=1
          fi
          if [[ "${STEPS_LINKCHECK_OUTPUTS_PERMANENT_REDIRECTS_COUNT}" != 0 ]]; then
              echo "Expected permanent-redirects-count=0"
              EXIT=1
          fi
          exit $EXIT
        env:
          STEPS_LINKCHECK_OUTPUTS_BROKEN_LINKS_COUNT: ${{ steps.linkcheck.outputs.broken-links-count }}
          STEPS_LINKCHECK_OUTPUTS_PERMANENT_REDIRECTS_COUNT: ${{ steps.linkcheck.outputs.permanent-redirects-count }}

  # Provides a single status_all check that can be used in GitHub branch
  # protection rules instead of having to list each matrix job
  # https://github.community/t/status-check-for-a-matrix-jobs/127354/7
  status_all:
    name: Status
    runs-on: ubuntu-24.04
    needs:
      - lint
      - test_linkcheck

    steps:
      # If we get here we know all dependent jobs passed
      - name: Check matrix status
        run: |
          echo OK
